name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        keycloak: ["4.8.3.Final", "5.0.0", "6.0.1", "7.0.1", "8.0.1", "9.0.0"]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Test
        run: |
          cd testing
          docker-compose up -d
          cd ..
          npm test
        env:
          KEYCLOAK_VERSION: ${{ matrix.keycloak }}
          CI: true
